import forms from "@tailwindcss/forms";

/** @type {import('tailwindcss').Config} */
const tailwindConfig = {
    theme: {
        extend: {
            colors: {
                primary: "#00113a",
                "primary-container": "#002366",
                "primary-fixed": "#dbe1ff",
                "primary-fixed-dim": "#b3c5ff",
                "on-primary": "#ffffff",
                "on-primary-fixed": "#00174a",
                "on-primary-fixed-variant": "#2a4386",
                secondary: "#775a19",
                "secondary-container": "#fed488",
                "secondary-fixed": "#ffdea5",
                "secondary-fixed-dim": "#e9c176",
                "on-secondary": "#ffffff",
                "on-secondary-container": "#785a1a",
                "on-secondary-fixed": "#261900",
                "on-secondary-fixed-variant": "#5d4201",
                tertiary: "#121515",
                "tertiary-container": "#272929",
                "tertiary-fixed": "#e2e2e2",
                "tertiary-fixed-dim": "#c6c6c7",
                "on-tertiary": "#ffffff",
                "on-tertiary-fixed": "#1a1c1c",
                "on-tertiary-fixed-variant": "#454747",
                error: "#ba1a1a",
                "error-container": "#ffdad6",
                "on-error": "#ffffff",
                "on-error-container": "#93000a",
                background: "#f9f9f9",
                surface: "#f9f9f9",
                "surface-dim": "#dadada",
                "surface-bright": "#f9f9f9",
                "surface-container-lowest": "#ffffff",
                "surface-container-low": "#f3f3f3",
                "surface-container": "#eeeeee",
                "surface-container-high": "#e8e8e8",
                "surface-container-highest": "#e2e2e2",
                "surface-variant": "#e2e2e2",
                "on-surface": "#1a1c1c",
                "on-surface-variant": "#444650",
                outline: "#757682",
                "outline-variant": "#c5c6d2",
                "inverse-surface": "#2f3131",
                "inverse-on-surface": "#f1f1f1",
                "inverse-primary": "#b3c5ff",
                "surface-tint": "#435b9f",
            },
            fontFamily: {
                headline: ["var(--font-newsreader)", "Newsreader", "serif"],
                body: ["var(--font-manrope)", "Manrope", "sans-serif"],
                label: ["var(--font-manrope)", "Manrope", "sans-serif"],
            },
            borderRadius: {
                DEFAULT: "0.125rem",
                lg: "0.25rem",
                xl: "0.5rem",
                full: "0.75rem",
            },
        },
    },
    plugins: [forms],
};

export default tailwindConfig;